version: "3"

services:
  frontend:
    image: ghcr.io/vitruvius-editor/vitruvius-editor-frontend:latest
    depends_on:
      - backend
    network_mode: host

  backend:
    image: ghcr.io/vitruvius-editor/vitruvius-editor-backend:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/myapp # Change db to localhost
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    network_mode: host

  db:
    image: postgres:17.2
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=myapp
    volumes:
      - db-data:/var/lib/postgresql/data
    network_mode: host # Use host network

  vitruvius:
    image: ghcr.io/vitruvius-editor/vitruvius-server:latest
    network_mode: host # Use host network

volumes:
  db-data:
