version: "3"

services:
  frontend:
    image: ghcr.io/vitruvius-editor/vitruvius-editor-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    network_mode: host

  backend:
    image: ghcr.io/vitruvius-editor/vitruvius-editor-backend:latest
    ports:
      - "8080:8080"
    network_mode: host

  vitruvius:
    image: ghcr.io/vitruvius-editor/vitruvius-server:latest
    network_mode: host # Use host network

