name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build Frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: false
        tags: vitruvius-editor-frontend:latest
        
    - name: Build Backend Docker image  
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: false
        tags: vitruvius-editor-backend:latest

    - name: Build Test Server Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./vitruv_server
        file: ./vitruv_server/Dockerfile
        push: false
        tags: vitruvius-server:latest
        
